### ISSUE TITLE
MUSHOP not accepting order above $ 100

### ISSUE THREAD

**Issue by karthiksuku** [oracle-quickstart/oci-cloudnative#283] opened 2021-07-16 02:50 UTC
while checkout to place order MUSHOP does not accept order above $ 100 value

**Comment by jeevanjoseph** [comment] 2021-07-16 04:30
This is by design. Take a look at payments app, and you will see an explicit validation that fails payments for above a certain dollar amount. 

This exists to showcase how parts of the system can be patched in a microservice environment, by rolling out a new version of only the payments service without touching anything else.

**Comment by karthiksuku** [comment] 2021-07-16 07:44
thanks Jeevan .It makes sence -  Is there an guide documentation on how I can modify payment service.

**Comment by junior** [comment] 2021-07-16 15:21
Out cat risk manager specialists concluded that any order over $105 is too risk for the MuShop cashflow, so the limit of $105 was hardcoded on the payment service: https://github.com/oracle-quickstart/oci-cloudnative/blob/5aab22041bf1c19da2599ba6402f0776df6cb7f6/src/payment/cmd/main.go#L28

If your accounting team thinks that you can handle more than that, you need to create a new build of the payment service, push to your OCIR and change the manifest to use the new service.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/551007/125970911-f1fe7f76-6992-4b47-9036-ea20dc9f4e21.png">

**Comment by jeevanjoseph** [comment] 2021-07-18 06:59
closing. payment service code is linked above.

**Closed by jeevanjoseph** 2021-07-18 06:59 UTC
