### ISSUE TITLE
Apply Error During Initial Creation

### ISSUE THREAD

**Issue by fmanzara** [oracle-quickstart/oci-cloudnative#110] opened 2020-02-18 23:21 UTC
RMJ Job apply error of Resource Type ORM Jobs:

oci_core_instance.app-instance[0]: Still creating... [2m0s elapsed]
Error: Service error:InternalError. Out of host capacity.. http status code: 500. Opc request id: xxxx
  on main.tf line 11, in resource "oci_core_instance"" ""app-instance" 
  11: resource "oci_core_instance"" ""app-instance" {

**Comment by jeevanjoseph** [comment] 2020-02-18 23:38
@fmanzara - can you make sure you are in the home region (the region drop down on the top right in the console will identify your home region).

If you are in your home region, simply try again ? The error message indicates that this is a temporary condition.

**Comment by jeevanjoseph** [comment] 2020-03-02 16:19
bump @fmanzara

**Comment by jeevanjoseph** [comment] 2020-05-07 23:36
Closing - please feel free to reopen if the issue is still persisting.

**Closed by jeevanjoseph** 2020-05-07 23:36 UTC
